//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Czlowiek.cpp
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#include "Czlowiek.h"

Czlowiek::Czlowiek(string Imie, string Nazwisko, int Pesel) {
    this->Imie = Imie;
    this->Nazwisko = Nazwisko;
    this->Pesel = Pesel;
}

void Czlowiek::SetImie(string Imie) {
    Imie = Imie;
}

void Czlowiek::SetNazwisko(string Nazwisko) {
    Nazwisko = Nazwisko;
}

string Czlowiek::GetImie() {
    return Imie;
}

string Czlowiek::GetNazwisko() {
    return Nazwisko;
}

int Czlowiek::GetPesel() {
    return Pesel;
}

