//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Czlowiek.h
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#if !defined(_CZLOWIEK_H)
#define _CZLOWIEK_H

#include <string>
using namespace std;

class Czlowiek {
public:
	Czlowiek(string Imie, string Nazwisko, int Pesel);
	void SetImie(string Imie);
	void SetNazwisko(string Nazwisko);
    string GetImie();
    string GetNazwisko();
    int GetPesel();
private:
	string Imie;
	string Nazwisko;
	int Pesel;
};

#endif  //_CZLOWIEK_H
