//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Nauczyciel.cpp
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#include "Nauczyciel.h"

Nauczyciel::Nauczyciel(string Imie, string Nazwisko, int Pesel, string Specializacja, float Pensja): Czlowiek(Imie, Nazwisko, Pesel) {
    this->Specializacja = Specializacja;
    this->Pensja = Pensja;
}
void Nauczyciel::SetSpecializacja(string Specializacja) {
    Specializacja = Specializacja;
}

void Nauczyciel::SetPensja(float Ilosc) {
    Pensja = Ilosc;
}

string Nauczyciel::GetSpecializacja() {
    return Specializacja;
}

float Nauczyciel::GetPensja() {
    return Pensja;
}

