//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Nauczyciel.h
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#if !defined(_NAUCZYCIEL_H)
#define _NAUCZYCIEL_H

#include "Czlowiek.h"
#include <string>
using namespace std;

class Nauczyciel : public Czlowiek {
public:
	string Specializacja;
	float Pensja;
    Nauczyciel(string Imie, string Nazwisko, int Pesel, string Specializacja, float Pensja);
    ~Nauczyciel();
	void SetSpecializacja(string Specializacja);
	void SetPensja(float Ilosc);
    string GetSpecializacja();
    float GetPensja();
};

#endif  //_NAUCZYCIEL_H
